# Generated by Django 5.2.2 on 2025-06-05 22:45

import herramientas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('bueno', 'Buen estado'), ('regular', 'Estado regular'), ('malo', 'Mal estado')], default='bueno', max_length=10)),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('prestada', 'Prestada'), ('mantenimiento', 'En mantenimiento'), ('inactiva', 'Inactiva')], default='disponible', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen de la herramienta', null=True, upload_to=herramientas.models.imagen_herramienta_path)),
            ],
        ),
    ]
