# Generated by Django 5.2.2 on 2025-06-05 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('bueno', 'Buen estado'), ('regular', 'Estado regular'), ('malo', 'Mal estado')], default='bueno', max_length=10)),
                ('disponibilidad', models.CharField(choices=[('disponible', 'Disponible'), ('prestada', 'Prestada'), ('mantenimiento', 'En mantenimiento'), ('inactiva', 'Inactiva')], default='disponible', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herramientas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
