# Generated by Django 5.2.2 on 2025-06-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0005_alter_herramienta_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herramienta',
            name='foto',
        ),
        migrations.AddField(
            model_name='herramienta',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la herramienta', null=True, upload_to='herramientas/'),
        ),
    ]
