# Generated by Django 5.2.2 on 2025-06-05 16:13

import herramientas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0006_remove_herramienta_foto_herramienta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen de la herramienta', null=True, upload_to=herramientas.models.imagen_herramienta_path),
        ),
    ]
