# Generated by Django 5.2.2 on 2025-06-05 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prestamos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='prestatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_solicitados', to=settings.AUTH_USER_MODEL),
        ),
    ]
